### ISSUE TITLE
Error on fresh cloned repo

### ISSUE THREAD

**Issue by minfawang** [apollostack/apollo-starter-kit#4]
I'm trying to follow the tutorial on Medium. To reproduce the error, just do
~~~shell
git clone https://github.com/apollostack/apollo-starter-kit.git
cd apollo-starter-kit
npm install
npm start
~~~

It gives me the following error message:
~~~shell
⇒  npm start

> apollo-starter-kit@0.1.0 start /Users/voiceup/Git/tutorials/apollo-starter-kit
> nodemon ./server.js --exec babel-node

[nodemon] 1.9.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node ./server.js`
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server.__dirname.Server.Server._listen2 (net.js:1230:14)
    at listen (net.js:1266:10)
    at Server.__dirname.Server.Server.listen (net.js:1362:5)
    at EventEmitter.listen (/Users/voiceup/Git/tutorials/apollo-starter-kit/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (server.js:15:15)
    at Module._compile (module.js:413:34)
    at loader (/Users/voiceup/Git/tutorials/apollo-starter-kit/node_modules/babel-register/lib/node.js:126:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/voiceup/Git/tutorials/apollo-starter-kit/node_modules/babel-register/lib/node.js:136:7)
[nodemon] app crashed - waiting for file changes before starting...
~~~

Is there anything I'm missing?

**Comment by helfer** [comment]
The EADDRINUSE error usually means that another process is already using port 8080, so try changing the port in server.js to something else, for example 3000.

**Comment by minfawang** [comment]
Oops, that seems to be the case. Thanks for the prompt response!!

**Comment by helfer** [comment]
No problem, glad you got it working! Don't hesitate to let me know if you run into any other issues, because chances are that other people might run into the same issues, so it's good if can update the tutorial to avoid those issues.
